title: BML
description: BML Blog
author: Seockhun Bae, Hyucksoon Jang
logo: /static/img/logo.png
github: https://github.com/s-hun
about: Bioinformatics Machine Learning

baseurl: ""
url: "https://bml.cbnu.ac.kr"

# allowsearch: true
allowsearch: false

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
